"use client";

import { useState } from "react";

interface CleanseCertificateProps {
  scanId: string;
  senderCount: number;
  messageCount: number;
  hoursSavedYearly: number;
  co2SavedGrams: number;
}

export function CleanseCertificate({
  scanId,
  senderCount,
  messageCount,
  hoursSavedYearly,
  co2SavedGrams,
}: CleanseCertificateProps) {
  const [copied, setCopied] = useState(false);

  const shareText = `I just banished ${senderCount} spam demons and silenced ~${messageCount} promotional emails with InboxExorcist 🕯️ Reclaiming ${hoursSavedYearly} hours/year with zero email deletion. https://inboxexorcist.com`;

  function copySummary() {
    navigator.clipboard.writeText(shareText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }

  function downloadSvgBadge() {
    const svgContent = `
<svg width="600" height="340" viewBox="0 0 600 340" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="600" height="340" rx="24" fill="#090A0F"/>
  <rect x="2" y="2" width="596" height="336" rx="22" stroke="#F59E0B" stroke-width="2" stroke-opacity="0.3"/>
  <circle cx="300" cy="50" r="28" fill="#F59E0B" fill-opacity="0.1"/>
  <text x="300" y="58" font-size="24" text-anchor="middle" fill="#F59E0B">🕯️</text>
  <text x="300" y="105" font-family="system-ui, sans-serif" font-size="22" font-weight="bold" fill="#FFFFFF" text-anchor="middle">OFFICIAL INBOX EXORCISM SEAL</text>
  <text x="300" y="128" font-family="monospace" font-size="12" fill="#9CA3AF" text-anchor="middle">SESSION ID: ${scanId.substring(0, 18)}</text>
  
  <rect x="40" y="150" width="160" height="90" rx="12" fill="#11131A" stroke="#FFFFFF" stroke-opacity="0.1"/>
  <text x="120" y="185" font-family="monospace" font-size="28" font-weight="bold" fill="#F59E0B" text-anchor="middle">${senderCount}</text>
  <text x="120" y="215" font-family="system-ui, sans-serif" font-size="11" fill="#9CA3AF" text-anchor="middle">DEMONS BANISHED</text>

  <rect x="220" y="150" width="160" height="90" rx="12" fill="#11131A" stroke="#FFFFFF" stroke-opacity="0.1"/>
  <text x="300" y="185" font-family="monospace" font-size="28" font-weight="bold" fill="#06B6D4" text-anchor="middle">${messageCount}</text>
  <text x="300" y="215" font-family="system-ui, sans-serif" font-size="11" fill="#9CA3AF" text-anchor="middle">PROMOS QUIETED</text>

  <rect x="400" y="150" width="160" height="90" rx="12" fill="#11131A" stroke="#FFFFFF" stroke-opacity="0.1"/>
  <text x="480" y="185" font-family="monospace" font-size="28" font-weight="bold" fill="#10B981" text-anchor="middle">${hoursSavedYearly}h</text>
  <text x="480" y="215" font-family="system-ui, sans-serif" font-size="11" fill="#9CA3AF" text-anchor="middle">HOURS RECLAIMED/YR</text>

  <text x="300" y="275" font-family="system-ui, sans-serif" font-size="12" fill="#10B981" text-anchor="middle">✓ ZERO-DELETE INVARIANT VERIFIED • 100% REVERSIBLE</text>
  <text x="300" y="305" font-family="system-ui, sans-serif" font-size="11" fill="#6B7280" text-anchor="middle">Generated by InboxExorcist.com • Gmail Cleanse Authority</text>
</svg>`;

    const blob = new Blob([svgContent], { type: "image/svg+xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `exorcism-seal-${scanId.substring(0, 8)}.svg`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}`;

  return (
    <div className="glass-card glow-amber rounded-3xl p-6 sm:p-8 border-amber-500/30">
      <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
        <div>
          <div className="inline-flex items-center gap-2 rounded-full bg-amber-500/10 px-3 py-1 text-xs font-bold text-amber-400 border border-amber-500/20">
            <span>🕯️</span> Verified Exorcism Seal
          </div>
          <h2 className="mt-3 text-2xl sm:text-3xl font-extrabold text-white">
            Share Your Cleanse Victory
          </h2>
          <p className="mt-2 text-sm text-zinc-300 max-w-xl">
            You silenced <strong>{senderCount} noise demons</strong> and preserved your focus. Share your official certificate or export a verifiable SVG proof badge.
          </p>

          <div className="mt-4 flex flex-wrap gap-4 text-xs text-zinc-400">
            <span className="flex items-center gap-1.5 text-emerald-400">
              <span>🌱</span> {co2SavedGrams}g CO2/yr prevented
            </span>
            <span className="flex items-center gap-1.5 text-cyan-400">
              <span>⚡</span> ~{messageCount * 3} notification alerts silenced
            </span>
          </div>
        </div>

        <div className="flex flex-wrap gap-3 items-center">
          <a
            href={twitterUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-sky-500 px-5 text-xs font-bold text-white shadow-md hover:bg-sky-400 transition"
          >
            <span>𝕏</span> Share on X
          </a>

          <button
            type="button"
            onClick={copySummary}
            className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-white/20 bg-white/5 px-4 text-xs font-semibold text-white hover:bg-white/10 transition"
          >
            <span>📋</span> {copied ? "Copied to Clipboard!" : "Copy Summary"}
          </button>

          <button
            type="button"
            onClick={downloadSvgBadge}
            className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-amber-500/40 bg-amber-500/10 px-4 text-xs font-bold text-amber-300 hover:bg-amber-500/20 transition"
          >
            <span>📥</span> Download SVG Seal
          </button>
        </div>
      </div>
    </div>
  );
}
