import type { FailureScenario } from '@/types'

export const failureScenarios: FailureScenario[] = [
  // FS-01: Rate limiting (429)
  {
    id: 'FS-01',
    scenario: 'Rate limiting blocks review fetch',
    trigger: 'HTTP 429 Too Many Requests',
    expectedBehavior: 'Backoff, retry with delay, report degraded',
    badBehavior: 'Silently return empty results',
    fix: 'Implement exponential backoff with max 3 retries',
    userMessage: 'Review data is temporarily rate-limited. Results may be incomplete.',
    confidenceImpact: 20,
    testCase: 'Mock 429 response → verify retry → verify degraded output',
  },
  // FS-02: CAPTCHA challenge
  {
    id: 'FS-02',
    scenario: 'CAPTCHA blocks automated access',
    trigger: 'CAPTCHA page detected in HTML',
    expectedBehavior: 'Detect CAPTCHA, return UNKNOWN with explanation',
    badBehavior: 'Parse CAPTCHA page as review data',
    fix: 'Detect CAPTCHA keywords/forms, return UNKNOWN',
    userMessage: 'Unable to access reviews — the site requires human verification.',
    confidenceImpact: 50,
    testCase: 'Mock CAPTCHA HTML → verify UNKNOWN verdict',
  },
  // FS-03: Region redirect
  {
    id: 'FS-03',
    scenario: 'URL redirects to different region',
    trigger: 'Response URL differs from request URL',
    expectedBehavior: 'Follow redirect, normalize region, note in limitations',
    badBehavior: 'Treat redirected content as original',
    fix: 'Track redirect chain, normalize region codes',
    userMessage: 'Reviews shown may be from a different regional store.',
    confidenceImpact: 10,
    testCase: 'Mock redirect → verify region normalization',
  },
  // FS-04: Empty 200 (out of stock / delisted)
  {
    id: 'FS-04',
    scenario: 'Product delisted or out of stock returns 200 with no reviews',
    trigger: '200 OK but review container empty or "not available" text',
    expectedBehavior: 'Detect empty state, return UNKNOWN',
    badBehavior: 'Return BUY verdict with zero reviews',
    fix: 'Check for product availability indicators before parsing',
    userMessage: 'This product appears unavailable. No review data to analyze.',
    confidenceImpact: 40,
    testCase: 'Mock 200 with "out of stock" → verify UNKNOWN',
  },
  // FS-05: WAF 403 block
  {
    id: 'FS-05',
    scenario: 'Web Application Firewall blocks request',
    trigger: '403 Forbidden with WAF signature',
    expectedBehavior: 'Detect WAF, retry with alternate strategy, report degraded',
    badBehavior: 'Treat 403 as no reviews exist',
    fix: 'Detect WAF patterns, try mobile UA, report limitation',
    userMessage: 'Access to reviews was restricted. Results may be limited.',
    confidenceImpact: 30,
    testCase: 'Mock 403 WAF response → verify retry → degraded output',
  },
  // FS-06: DOM mutation / dynamic content
  {
    id: 'FS-06',
    scenario: 'Reviews loaded via JavaScript after initial render',
    trigger: 'Static HTML has no review data, only loading placeholders',
    expectedBehavior: 'Detect missing data, try API endpoint fallback',
    badBehavior: 'Parse loading spinner as review content',
    fix: 'Check for review container content, try known API patterns',
    userMessage: 'Reviews load dynamically. Some data may not be accessible.',
    confidenceImpact: 25,
    testCase: 'Mock empty DOM with loading div → verify detection',
  },
  // FS-07: Lazy-loaded reviews
  {
    id: 'FS-07',
    scenario: 'Reviews require scroll/pagination to load',
    trigger: 'Initial page has only first N reviews',
    expectedBehavior: 'Detect pagination, fetch additional pages (server-safe)',
    badBehavior: 'Analyze only first page as complete dataset',
    fix: 'Detect pagination controls, fetch up to reasonable limit',
    userMessage: 'Only a subset of reviews was accessible.',
    confidenceImpact: 15,
    testCase: 'Mock paginated HTML → verify multi-page fetch attempt',
  },
  // FS-08: Shadow DOM encapsulation
  {
    id: 'FS-08',
    scenario: 'Reviews rendered inside Shadow DOM',
    trigger: 'Standard selectors find nothing, shadow root contains data',
    expectedBehavior: 'Try shadow DOM traversal where possible',
    badBehavior: 'Return empty results without checking shadow DOM',
    fix: 'Check for shadow roots, query within them',
    userMessage: 'Review content is embedded in a way that limits access.',
    confidenceImpact: 20,
    testCase: 'Mock shadow DOM structure → verify traversal attempt',
  },
  // FS-09: Headless detection
  {
    id: 'FS-09',
    scenario: 'Site detects headless browser and serves different content',
    trigger: 'navigator.webdriver checks, missing plugins, wrong fonts',
    expectedBehavior: 'Harden request headers, mask headless indicators',
    badBehavior: 'Receive degraded content without detection',
    fix: 'Set realistic headers, remove webdriver property indicators',
    userMessage: 'The site may have served limited content to automated access.',
    confidenceImpact: 20,
    testCase: 'Verify headers include realistic User-Agent, Accept, etc.',
  },
  // FS-10: Anti-bot JavaScript challenge
  {
    id: 'FS-10',
    scenario: 'Site requires JS execution to pass challenge',
    trigger: 'HTML contains JS challenge/obfuscation code',
    expectedBehavior: 'Detect challenge, return UNKNOWN',
    badBehavior: 'Try to parse challenge page as content',
    fix: 'Detect challenge patterns (cookie set via JS, obfuscated code)',
    userMessage: 'This site requires JavaScript verification. Unable to access reviews.',
    confidenceImpact: 50,
    testCase: 'Mock JS challenge page → verify UNKNOWN',
  },
  // FS-11: Honeypot hidden reviews
  {
    id: 'FS-11',
    scenario: 'Hidden/fake reviews injected to mislead scrapers',
    trigger: 'Reviews with display:none, zero-height containers, invisible text',
    expectedBehavior: 'Detect and exclude hidden elements from analysis',
    badBehavior: 'Count hidden reviews as real data',
    fix: 'Check element visibility, exclude hidden nodes',
    userMessage: 'Some review content was filtered as potentially misleading.',
    confidenceImpact: 10,
    testCase: 'Mock HTML with hidden divs → verify exclusion',
  },
  // FS-12: Mixed content / partial data
  {
    id: 'FS-12',
    scenario: 'Some review fields present, others missing',
    trigger: 'Reviews with ratings but no text, or text but no dates',
    expectedBehavior: 'Use available data, note missing fields',
    badBehavior: 'Discard entire review due to one missing field',
    fix: 'Partial parsing with field-level completeness tracking',
    userMessage: 'Some review details were incomplete.',
    confidenceImpact: 10,
    testCase: 'Mock reviews with missing fields → verify partial parse',
  },
  // FS-13: Encoding issues
  {
    id: 'FS-13',
    scenario: 'Non-UTF8 encoding corrupts review text',
    trigger: 'ISO-8859-1, Windows-1252, or other encodings',
    expectedBehavior: 'Detect encoding, convert properly',
    badBehavior: 'Return garbled text as review content',
    fix: 'Check Content-Type charset, decode accordingly',
    userMessage: 'Some review text may have encoding issues.',
    confidenceImpact: 5,
    testCase: 'Mock non-UTF8 response → verify proper decoding',
  },
  // FS-14: Timeout during fetch
  {
    id: 'FS-14',
    scenario: 'Request timeout during fetch',
    trigger: 'Fetch exceeds timeout threshold',
    expectedBehavior: 'Catch timeout, try fallback strategy, report degraded',
    badBehavior: 'Hang indefinitely or crash',
    fix: 'Set timeout, catch error, try Tier2 strategy',
    userMessage: 'The review page timed out. Results may be incomplete.',
    confidenceImpact: 25,
    testCase: 'Mock slow response → verify timeout → fallback',
  },
  // FS-15: Response too large
  {
    id: 'FS-15',
    scenario: 'Response exceeds size limit',
    trigger: 'HTML body exceeds max size',
    expectedBehavior: 'Truncate safely, parse what is available',
    badBehavior: 'Crash or OOM on huge response',
    fix: 'Enforce size limit, parse truncated content',
    userMessage: 'The page was very large. Only partial content was processed.',
    confidenceImpact: 15,
    testCase: 'Mock oversized response → verify safe truncation',
  },
  // FS-16: JSON-LD missing or malformed
  {
    id: 'FS-16',
    scenario: 'Structured data not present or invalid',
    trigger: 'No application/ld+json script or invalid JSON',
    expectedBehavior: 'Fall back to DOM parsing',
    badBehavior: 'Crash on JSON parse error',
    fix: 'Try JSON-LD first, catch parse errors, fall back to DOM',
    userMessage: 'Structured data was unavailable. Parsing page content directly.',
    confidenceImpact: 10,
    testCase: 'Mock malformed JSON-LD → verify DOM fallback',
  },
  // FS-17: Review bombing (sudden influx)
  {
    id: 'FS-17',
    scenario: 'Mass of reviews posted in short time window',
    trigger: 'Many reviews within hours/days of each other',
    expectedBehavior: 'Detect temporal clustering, flag as suspicious',
    badBehavior: 'Treat all reviews as organic',
    fix: 'Calculate review velocity, flag bursts',
    userMessage: 'Unusual review activity detected in a short time period.',
    confidenceImpact: 15,
    testCase: 'Mock reviews all on same date → verify burst detection',
  },
  // FS-18: Identical review text
  {
    id: 'FS-18',
    scenario: 'Multiple reviews with same or near-identical text',
    trigger: 'Duplicate or near-duplicate review bodies',
    expectedBehavior: 'Detect duplicates, flag as suspicious',
    badBehavior: 'Count duplicates as independent reviews',
    fix: 'Compute text similarity, group duplicates',
    userMessage: 'Several reviews appear to be copies of each other.',
    confidenceImpact: 15,
    testCase: 'Mock identical reviews → verify duplicate detection',
  },
  // FS-19: Sentiment manipulation
  {
    id: 'FS-19',
    scenario: 'Reviews with extreme sentiment but vague content',
    trigger: '5-star with "great!" or 1-star with "terrible!" and no detail',
    expectedBehavior: 'Flag low-effort extreme reviews',
    badBehavior: 'Weight short extreme reviews equally with detailed ones',
    fix: 'Score review depth, downweight shallow extremes',
    userMessage: 'Some reviews lacked detail to support their rating.',
    confidenceImpact: 10,
    testCase: 'Mock short extreme reviews → verify depth scoring',
  },
  // FS-20: Verified purchase ratio anomaly
  {
    id: 'FS-20',
    scenario: 'Very low ratio of verified purchases',
    trigger: 'Most reviews lack verified purchase badges',
    expectedBehavior: 'Flag low verification rate',
    badBehavior: 'Treat unverified same as verified',
    fix: 'Track verified ratio, adjust confidence',
    userMessage: 'Few reviews show verified purchase status.',
    confidenceImpact: 15,
    testCase: 'Mock 90% unverified → verify flag',
  },
  // FS-21: New reviewer accounts
  {
    id: 'FS-21',
    scenario: 'Many reviews from newly created accounts',
    trigger: 'Reviewer profiles show recent creation dates',
    expectedBehavior: 'Flag cluster of new accounts',
    badBehavior: 'Ignore account age signals',
    fix: 'Track reviewer account age distribution',
    userMessage: 'Several reviews came from recently created accounts.',
    confidenceImpact: 10,
    testCase: 'Mock new account indicators → verify detection',
  },
  // FS-22: Single-product reviewers
  {
    id: 'FS-22',
    scenario: 'Reviewers who only reviewed this one product',
    trigger: 'Reviewer history shows only one review ever',
    expectedBehavior: 'Flag as potentially incentivized',
    badBehavior: 'Treat single-product reviewers as normal',
    fix: 'Track reviewer activity breadth',
    userMessage: 'Some reviewers have only reviewed this product.',
    confidenceImpact: 10,
    testCase: 'Mock single-review accounts → verify flag',
  },
  // FS-23: Keyword stuffing
  {
    id: 'FS-23',
    scenario: 'Reviews stuffed with product keywords',
    trigger: 'Unnatural repetition of brand/product terms',
    expectedBehavior: 'Detect keyword density anomalies',
    badBehavior: 'Treat keyword-stuffed reviews as genuine',
    fix: 'Calculate keyword frequency, flag outliers',
    userMessage: 'Some reviews contain unusual keyword repetition.',
    confidenceImpact: 10,
    testCase: 'Mock keyword-stuffed review → verify detection',
  },
  // FS-24: Geographic impossibility
  {
    id: 'FS-24',
    scenario: 'Reviewers claim locations inconsistent with product availability',
    trigger: 'Reviewer location vs product regional availability mismatch',
    expectedBehavior: 'Flag geo inconsistencies',
    badBehavior: 'Ignore geographic signals',
    fix: 'Compare reviewer locations with product availability',
    userMessage: 'Some reviewer locations seem inconsistent with product availability.',
    confidenceImpact: 10,
    testCase: 'Mock geo mismatch → verify detection',
  },
  // FS-25: Rating distribution anomaly
  {
    id: 'FS-25',
    scenario: 'Bimodal rating distribution (mostly 5-star and 1-star)',
    trigger: 'U-shaped rating histogram',
    expectedBehavior: 'Flag polarized distribution',
    badBehavior: 'Use average rating without noting polarization',
    fix: 'Analyze rating distribution shape',
    userMessage: 'Reviews are heavily polarized between very positive and very negative.',
    confidenceImpact: 15,
    testCase: 'Mock bimodal ratings → verify detection',
  },
  // FS-26: Language mismatch
  {
    id: 'FS-26',
    scenario: 'Reviews in languages inconsistent with product market',
    trigger: 'Product sold in US but reviews primarily in other languages',
    expectedBehavior: 'Flag language distribution anomalies',
    badBehavior: 'Ignore language signals',
    fix: 'Detect review languages, compare with expected market',
    userMessage: 'Review languages differ from the expected market.',
    confidenceImpact: 10,
    testCase: 'Mock language mismatch → verify detection',
  },
  // FS-27: Timestamp manipulation
  {
    id: 'FS-27',
    scenario: 'Reviews backdated or future-dated',
    trigger: 'Review dates before product launch or in the future',
    expectedBehavior: 'Flag impossible timestamps',
    badBehavior: 'Accept all timestamps at face value',
    fix: 'Compare review dates with product listing date',
    userMessage: 'Some review dates appear inconsistent with the product timeline.',
    confidenceImpact: 15,
    testCase: 'Mock pre-launch reviews → verify detection',
  },
  // FS-28: Helpful vote manipulation
  {
    id: 'FS-28',
    scenario: 'Suspicious patterns in helpful vote counts',
    trigger: 'All positive reviews have high helpful votes, negative have zero',
    expectedBehavior: 'Flag helpful vote anomalies',
    badBehavior: 'Use helpful votes as quality signal without scrutiny',
    fix: 'Analyze correlation between rating and helpful votes',
    userMessage: 'Helpful vote patterns appear uneven across review ratings.',
    confidenceImpact: 10,
    testCase: 'Mock skewed helpful votes → verify detection',
  },
  // FS-29: Category mismatch
  {
    id: 'FS-29',
    scenario: 'Reviews discuss a different product than listed',
    trigger: 'Review content mentions different product names/features',
    expectedBehavior: 'Detect content mismatch with product title',
    badBehavior: 'Analyze irrelevant reviews',
    fix: 'Compare review content keywords with product title/description',
    userMessage: 'Some reviews may be for a different product variant.',
    confidenceImpact: 20,
    testCase: 'Mock mismatched review content → verify detection',
  },
  // FS-30: Seller review injection
  {
    id: 'FS-30',
    scenario: 'Seller or affiliate posts positive reviews',
    trigger: 'Reviews from accounts linked to seller',
    expectedBehavior: 'Flag potential self-reviews',
    badBehavior: 'Treat seller reviews as independent',
    fix: 'Cross-reference reviewer names with seller info',
    userMessage: 'Some reviews may be connected to the seller.',
    confidenceImpact: 20,
    testCase: 'Mock seller-linked reviews → verify detection',
  },
  // FS-31: Incentivized review patterns
  {
    id: 'FS-31',
    scenario: 'Reviews mention free product, discount, or incentive',
    trigger: 'Keywords like "free", "discount", "in exchange for", "honest review"',
    expectedBehavior: 'Detect incentive mentions, flag reviews',
    badBehavior: 'Ignore incentive disclosures',
    fix: 'Scan for incentive-related keywords',
    userMessage: 'Some reviews mention receiving the product at a discount.',
    confidenceImpact: 15,
    testCase: 'Mock incentive mentions → verify detection',
  },
  // FS-32: Template review structure
  {
    id: 'FS-32',
    scenario: 'Reviews follow identical structural patterns',
    trigger: 'Same paragraph structure, same pros/cons format across reviews',
    expectedBehavior: 'Detect structural similarity',
    badBehavior: 'Treat templated reviews as independent',
    fix: 'Analyze review structure patterns',
    userMessage: 'Several reviews follow a similar structure.',
    confidenceImpact: 10,
    testCase: 'Mock templated reviews → verify detection',
  },
  // FS-33: Image-only reviews
  {
    id: 'FS-33',
    scenario: 'Reviews contain only images with no text',
    trigger: 'Review body empty but has image attachments',
    expectedBehavior: 'Note image-only reviews, exclude from text analysis',
    badBehavior: 'Treat empty text as zero-sentiment review',
    fix: 'Detect image-only reviews, handle separately',
    userMessage: 'Some reviews contain only images without text.',
    confidenceImpact: 5,
    testCase: 'Mock image-only reviews → verify handling',
  },
  // FS-34: Review editing without notation
  {
    id: 'FS-34',
    scenario: 'Reviews edited after initial posting without edit history',
    trigger: 'Review shows updated date but no edit notation',
    expectedBehavior: 'Note edited reviews, flag if significant',
    badBehavior: 'Treat edited reviews as original',
    fix: 'Detect edit indicators, note in analysis',
    userMessage: 'Some reviews appear to have been edited after posting.',
    confidenceImpact: 5,
    testCase: 'Mock edited reviews → verify detection',
  },
  // FS-35: Cross-platform review migration
  {
    id: 'FS-35',
    scenario: 'Reviews imported from other platforms',
    trigger: 'Review metadata shows external source',
    expectedBehavior: 'Note imported reviews, note different verification standards',
    badBehavior: 'Treat imported reviews same as native',
    fix: 'Detect import indicators, adjust confidence',
    userMessage: 'Some reviews were imported from another platform.',
    confidenceImpact: 10,
    testCase: 'Mock imported review indicators → verify detection',
  },
  // FS-36: Seasonal product mismatch
  {
    id: 'FS-36',
    scenario: 'Reviews for seasonal product from wrong season',
    trigger: 'Winter product reviewed in summer, or vice versa',
    expectedBehavior: 'Note seasonal context mismatch',
    badBehavior: 'Ignore seasonal timing',
    fix: 'Compare review dates with product seasonality',
    userMessage: 'Review timing may not reflect typical seasonal use.',
    confidenceImpact: 5,
    testCase: 'Mock seasonal mismatch → verify detection',
  },
  // FS-37: Product variant confusion
  {
    id: 'FS-37',
    scenario: 'Reviews for different variants merged on same page',
    trigger: 'Reviews mention different sizes, colors, models',
    expectedBehavior: 'Detect variant mentions, note mixing',
    badBehavior: 'Treat all reviews as for the specific variant',
    fix: 'Extract variant mentions from reviews, note distribution',
    userMessage: 'Reviews may cover different product variants.',
    confidenceImpact: 15,
    testCase: 'Mock variant mentions → verify detection',
  },
  // FS-38: Bot-generated reviews
  {
    id: 'FS-38',
    scenario: 'Reviews generated by automated text generation',
    trigger: 'Unnatural language patterns, repetitive structures, AI markers',
    expectedBehavior: 'Flag potentially AI-generated reviews',
    badBehavior: 'Treat bot reviews as human',
    fix: 'Detect language patterns consistent with generation',
    userMessage: 'Some reviews show patterns consistent with automated generation.',
    confidenceImpact: 20,
    testCase: 'Mock AI-like text patterns → verify detection',
  },
  // FS-39: Review gating
  {
    id: 'FS-39',
    scenario: 'Only satisfied customers prompted to review',
    trigger: 'Review solicitation patterns favor positive experiences',
    expectedBehavior: 'Note potential review bias',
    badBehavior: 'Assume reviews represent all customers',
    fix: 'Flag potential selection bias in review collection',
    userMessage: 'The review collection process may favor positive feedback.',
    confidenceImpact: 15,
    testCase: 'Mock positive-skewed sample → verify bias flag',
  },
  // FS-40: Competitor sabotage
  {
    id: 'FS-40',
    scenario: 'Negative reviews from competitor-linked accounts',
    trigger: 'Cluster of negative reviews from accounts with competitor patterns',
    expectedBehavior: 'Flag potential competitor activity',
    badBehavior: 'Treat all negative reviews as genuine',
    fix: 'Detect clusters of negative reviews with suspicious patterns',
    userMessage: 'Some negative reviews show patterns that warrant caution.',
    confidenceImpact: 15,
    testCase: 'Mock competitor-like negative cluster → verify detection',
  },
  // FS-41: Review deletion manipulation
  {
    id: 'FS-41',
    scenario: 'Negative reviews selectively removed',
    trigger: 'Gap in review timeline, sudden drop in negative ratio',
    expectedBehavior: 'Note potential review curation',
    badBehavior: 'Assume all reviews are present',
    fix: 'Analyze review timeline for gaps',
    userMessage: 'The review timeline shows gaps that may indicate curation.',
    confidenceImpact: 10,
    testCase: 'Mock timeline gaps → verify detection',
  },
  // FS-42: Fake verified badges
  {
    id: 'FS-42',
    scenario: 'Verified purchase badges on non-verified reviews',
    trigger: 'Verified badge present but review content contradicts purchase',
    expectedBehavior: 'Cross-verify badge claims with review content',
    badBehavior: 'Trust all verified badges',
    fix: 'Flag inconsistencies between badge and content',
    userMessage: 'Some verified badges may not reflect actual purchases.',
    confidenceImpact: 15,
    testCase: 'Mock badge/content mismatch → verify detection',
  },
  // FS-43: Review hijacking
  {
    id: 'FS-43',
    scenario: 'Product listing repurposed with new product but old reviews',
    trigger: 'Product title changed but old reviews remain',
    expectedBehavior: 'Detect listing changes, flag review relevance',
    badBehavior: 'Treat old reviews as relevant to new product',
    fix: 'Compare review dates with listing change dates',
    userMessage: 'Some reviews may be for a previous version of this listing.',
    confidenceImpact: 25,
    testCase: 'Mock listing change indicators → verify detection',
  },
  // FS-44: Subscription trap reviews
  {
    id: 'FS-44',
    scenario: 'Reviews for subscription product don\'t mention recurring charges',
    trigger: 'Subscription product with reviews that don\'t mention ongoing costs',
    expectedBehavior: 'Flag missing subscription cost mentions',
    badBehavior: 'Ignore subscription context',
    fix: 'Detect subscription products, check for cost mentions',
    userMessage: 'Reviews may not reflect ongoing subscription costs.',
    confidenceImpact: 15,
    testCase: 'Mock subscription product without cost mentions → verify flag',
  },
  // FS-45: Counterfeit product reviews
  {
    id: 'FS-45',
    scenario: 'Reviews for counterfeit product mixed with genuine',
    trigger: 'Reviews mention quality differences, packaging issues',
    expectedBehavior: 'Flag reviews suggesting counterfeit concerns',
    badBehavior: 'Treat all reviews as for genuine product',
    fix: 'Scan for counterfeit-related keywords',
    userMessage: 'Some reviews raise questions about product authenticity.',
    confidenceImpact: 20,
    testCase: 'Mock counterfeit mentions → verify detection',
  },
  // FS-46: Warranty void reviews
  {
    id: 'FS-46',
    scenario: 'Reviews mention warranty issues not reflected in listing',
    trigger: 'Reviews mention voided warranty, denied claims',
    expectedBehavior: 'Extract warranty-related concerns',
    badBehavior: 'Ignore warranty signals in reviews',
    fix: 'Scan for warranty-related keywords and claims',
    userMessage: 'Some reviews mention warranty concerns.',
    confidenceImpact: 15,
    testCase: 'Mock warranty complaint reviews → verify extraction',
  },
  // FS-47: Safety concern reviews
  {
    id: 'FS-47',
    scenario: 'Reviews mention safety issues',
    trigger: 'Reviews mention injury, hazard, danger, recall',
    expectedBehavior: 'Flag safety-related reviews prominently',
    badBehavior: 'Bury safety concerns in general analysis',
    fix: 'Prioritize safety-related review detection',
    userMessage: 'Some reviews mention safety concerns that warrant attention.',
    confidenceImpact: 25,
    testCase: 'Mock safety concern reviews → verify prominent flagging',
  },
  // FS-48: Regulatory compliance reviews
  {
    id: 'FS-48',
    scenario: 'Reviews mention regulatory issues (FCC, CE, FDA)',
    trigger: 'Reviews mention certification problems, compliance failures',
    expectedBehavior: 'Flag regulatory concerns',
    badBehavior: 'Ignore regulatory signals',
    fix: 'Scan for regulatory keywords',
    userMessage: 'Some reviews mention regulatory or compliance concerns.',
    confidenceImpact: 15,
    testCase: 'Mock regulatory mentions → verify detection',
  },
  // FS-49: Data privacy concerns
  {
    id: 'FS-49',
    scenario: 'Reviews mention data collection, privacy issues',
    trigger: 'Reviews mention data sharing, tracking, privacy concerns',
    expectedBehavior: 'Flag privacy-related concerns',
    badBehavior: 'Ignore privacy signals',
    fix: 'Scan for privacy-related keywords',
    userMessage: 'Some reviews mention data privacy concerns.',
    confidenceImpact: 10,
    testCase: 'Mock privacy concern reviews → verify detection',
  },
  // FS-50: Complete site unavailability
  {
    id: 'FS-50',
    scenario: 'Entire review site is unreachable',
    trigger: 'DNS failure, connection refused, site down',
    expectedBehavior: 'Return UNKNOWN with clear explanation',
    badBehavior: 'Crash or return fake data',
    fix: 'Catch network errors, return UNKNOWN',
    userMessage: 'Unable to reach the review site. Please try again later.',
    confidenceImpact: 50,
    testCase: 'Mock network error → verify UNKNOWN with explanation',
  },
]

export function getFailureScenario(id: string): FailureScenario | undefined {
  return failureScenarios.find((fs) => fs.id === id)
}

export function getFailureByTrigger(trigger: string): FailureScenario | undefined {
  return failureScenarios.find((fs) =>
    fs.trigger.toLowerCase().includes(trigger.toLowerCase()),
  )
}

export function getAllFailureIds(): string[] {
  return failureScenarios.map((fs) => fs.id)
}
