import type { SenderCandidate } from "@/lib/domain";

export interface ProviderExporterResult {
  filename: string;
  mimeType: string;
  content: string;
  instructions: string;
}

/**
 * Exports Gmail XML filter file for manual or bulk import in Gmail settings.
 */
export function exportGmailFilterXml(
  candidates: SenderCandidate[],
  labelName = "InboxExorcist/Quieted",
): ProviderExporterResult {
  const domains = candidates
    .filter((c) => c.selectedByDefault && c.proposedAction !== "SKIP")
    .map((c) => `*@${c.senderDomain}`);

  const fromQuery = domains.length > 0 ? domains.join(" OR ") : "*@promotions.example.com";
  const updatedDate = new Date().toISOString();

  const content = `<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns='http://www.w3.org/2005/Atom' xmlns:apps='http://schemas.google.com/apps/2006'>
  <title>InboxExorcist Filters</title>
  <updated>${updatedDate}</updated>
  <author>
    <name>InboxExorcist</name>
    <email>support@inboxexorcist.com</email>
  </author>
  <entry>
    <category term='filter'></category>
    <title>InboxExorcist Noise Quiet Filter</title>
    <apps:property name='from' value='${fromQuery}'/>
    <apps:property name='shouldArchive' value='true'/>
    <apps:property name='label' value='${labelName}'/>
  </entry>
</feed>`;

  return {
    filename: "inboxexorcist-gmail-filters.xml",
    mimeType: "application/xml",
    content,
    instructions:
      "In Gmail, go to Settings ⚙️ → See all settings → Filters and Blocked Addresses → Import filters, then select this XML file.",
  };
}

/**
 * Exports RFC-5228 Sieve filter script compatible with ProtonMail, Fastmail, Hey, and custom IMAP servers.
 */
export function exportSieveScript(
  candidates: SenderCandidate[],
  folderName = "InboxExorcist/Quieted",
): ProviderExporterResult {
  const domains = candidates
    .filter((c) => c.selectedByDefault && c.proposedAction !== "SKIP")
    .map((c) => `"${c.senderDomain}"`);

  const domainList = domains.length > 0 ? domains.join(", ") : `"promo.example.com"`;

  const content = `# ==========================================
# Generated by InboxExorcist - Universal Exorcism Filter
# Compatible with ProtonMail, Fastmail, Hey, Posteo & Dovecot
# ==========================================
require ["fileinto", "envelope"];

if address :domain :is "from" [${domainList}] {
    fileinto "${folderName}";
}
`;

  return {
    filename: "inboxexorcist-rules.sieve",
    mimeType: "application/sieve",
    content,
    instructions:
      "In ProtonMail or Fastmail, go to Settings → Filters → Add Sieve Filter, and paste this script directly.",
  };
}

/**
 * Exports Apple Mail configuration script for macOS Mail / iCloud.
 */
export function exportAppleMailScript(
  candidates: SenderCandidate[],
): ProviderExporterResult {
  const domains = candidates
    .filter((c) => c.selectedByDefault && c.proposedAction !== "SKIP")
    .map((c) => c.senderDomain);

  const domainConditions = domains
    .map((d) => `make new rule condition with properties {rule type:from header, qualifier:contains, expression:"@${d}"}`)
    .join("\n        ");

  const content = `(*
  InboxExorcist Apple Mail Automation
  Run this script in Script Editor on macOS to automatically configure your Mail.app filter rule.
*)
tell application "Mail"
    set ruleName to "InboxExorcist Quieted Promos"
    if not (exists rule ruleName) then
        set newRule to make new rule with properties {name:ruleName, all conditions must be met:false, should move message:true}
        tell newRule
            ${domainConditions || 'make new rule condition with properties {rule type:from header, qualifier:contains, expression:"@example.com"}'}
        end tell
    end if
end tell
display dialog "InboxExorcist rule successfully configured in Apple Mail!" buttons {"OK"} default button "OK" with title "InboxExorcist"
`;

  return {
    filename: "setup-inboxexorcist-apple-mail.applescript",
    mimeType: "text/plain",
    content,
    instructions:
      "Open Script Editor on your Mac, paste this script, and click Run (▶) to create the rule automatically.",
  };
}

/**
 * Exports Microsoft Outlook & Office 365 sweep recipe JSON.
 */
export function exportOutlookRuleJson(
  candidates: SenderCandidate[],
  folderName = "InboxExorcist - Quieted",
): ProviderExporterResult {
  const domains = candidates
    .filter((c) => c.selectedByDefault && c.proposedAction !== "SKIP")
    .map((c) => c.senderDomain);

  const payload = {
    provider: "Microsoft Outlook / Office 365",
    ruleName: "InboxExorcist Quieted Promos",
    condition: {
      field: "senderAddressEndsWith",
      values: domains,
    },
    actions: {
      moveToFolder: folderName,
      markAsRead: false,
      stopProcessingMoreRules: true,
    },
    instructions: [
      "1. Open Outlook Web (outlook.office.com or outlook.live.com)",
      "2. Go to Settings ⚙️ → Mail → Rules → + Add new rule",
      `3. Name the rule: "InboxExorcist Quieted Promos"`,
      `4. Add condition: Sender address includes '@${domains[0] || "example.com"}'`,
      `5. Add action: Move to folder '${folderName}'`,
    ],
  };

  return {
    filename: "inboxexorcist-outlook-rules.json",
    mimeType: "application/json",
    content: JSON.stringify(payload, null, 2),
    instructions:
      "Follow the step-by-step Outlook rule recipe or import into your Microsoft 365 admin policy.",
  };
}
