import type { ScanRunWithCandidates } from "./domain.ts";

export function mockScan(): ScanRunWithCandidates {
  const now = new Date().toISOString();
  return {
    id: "mock",
    userId: "mock-user",
    status: "completed",
    query: "mock",
    messageCount: 184,
    candidateCount: 5,
    selectedCount: 3,
    skippedCount: 2,
    degraded: false,
    startedAt: now,
    finishedAt: now,
    candidates: [
      {
        id: "mock-1",
        scanRunId: "mock",
        userId: "mock-user",
        senderDomain: "deals.example",
        senderDisplayName: "Daily Deals",
        classification: "PROMOTIONAL_HIGH_CONFIDENCE",
        score: 90,
        reasons: ["List-Unsubscribe header exists", "High send frequency"],
        messageCount: 91,
        proposedAction: "UNSUBSCRIBE_THEN_FILTER",
        selectedByDefault: true,
        unsubscribeMethods: ["https"],
        createdAt: now,
      },
      {
        id: "mock-2",
        scanRunId: "mock",
        userId: "mock-user",
        senderDomain: "newsletter.example",
        senderDisplayName: "Morning Digest",
        classification: "NEWSLETTER_HIGH_CONFIDENCE",
        score: 85,
        reasons: ["Newsletter language", "Bulk/list headers present"],
        messageCount: 47,
        proposedAction: "QUIET_BY_FILTER",
        selectedByDefault: true,
        unsubscribeMethods: ["mailto"],
        createdAt: now,
      },
      {
        id: "mock-3",
        scanRunId: "mock",
        userId: "mock-user",
        senderDomain: "launches.example",
        senderDisplayName: "Product Updates",
        classification: "PROMOTIONAL_HIGH_CONFIDENCE",
        score: 82,
        reasons: ["Promotional language", "No-reply sender pattern"],
        messageCount: 34,
        proposedAction: "QUIET_BY_FILTER",
        selectedByDefault: true,
        unsubscribeMethods: [],
        createdAt: now,
      },
      {
        id: "mock-4",
        scanRunId: "mock",
        userId: "mock-user",
        senderDomain: "bank.example",
        senderDisplayName: "Bank Alerts",
        classification: "FINANCIAL_SAFE_SKIP",
        score: 15,
        reasons: ["Financial/security-sensitive keyword"],
        messageCount: 8,
        proposedAction: "SKIP",
        selectedByDefault: false,
        unsubscribeMethods: [],
        protectedReason: "Financial or tax sender",
        createdAt: now,
      },
      {
        id: "mock-5",
        scanRunId: "mock",
        userId: "mock-user",
        senderDomain: "orders.example",
        senderDisplayName: "Shipping Updates",
        classification: "TRANSACTIONAL_SAFE_SKIP",
        score: 22,
        reasons: ["Receipt, invoice, shipping, or order keyword"],
        messageCount: 4,
        proposedAction: "SKIP",
        selectedByDefault: false,
        unsubscribeMethods: ["https"],
        protectedReason: "Transactional sender",
        createdAt: now,
      },
    ],
  };
}
